#pragma once
// autogenerated from dotgen.hpp.j2

#include <string>

class FloatExprNode;
class IntegerExprNode;
class BoolExprNode;
class OrExprNode;
class AndExprNode;
class PrefixExprNode;
class BinExprNode;
class VarDeclNode;
class FnDefNode;
class FnParamNode;
class BlockNode;
class RootNode;
class AssignStNode;
class ReturnStNode;
class IfStNode;
class VarExprNode;
class FnCallExprNode;
class EmptyNode;

class DotGenerator {
  std::string output;

public:
  std::string getDotOutput();

  void generate(const FloatExprNode &astNode);
  void generate(const IntegerExprNode &astNode);
  void generate(const BoolExprNode &astNode);
  void generate(const OrExprNode &astNode);
  void generate(const AndExprNode &astNode);
  void generate(const PrefixExprNode &astNode);
  void generate(const BinExprNode &astNode);
  void generate(const VarDeclNode &astNode);
  void generate(const FnDefNode &astNode);
  void generate(const FnParamNode &astNode);
  void generate(const BlockNode &astNode);
  void generate(const RootNode &astNode);
  void generate(const AssignStNode &astNode);
  void generate(const ReturnStNode &astNode);
  void generate(const IfStNode &astNode);
  void generate(const VarExprNode &astNode);
  void generate(const FnCallExprNode &astNode);
  void generate(const EmptyNode &astNode);
};
